### ISSUE TITLE
ERROR on initial installation and startup

### ISSUE THREAD

**Issue by SlimeDog** [ZombieStriker/WorldChangeScreenRemover#1]
Spigot 1.12.2
WCSR 1.0.2

Nice idea, but a few issues.
```
[23:10:10] [Server thread/ERROR]: [WorldChangeScreenRemover] Could not log to /home/ram/Spigot/plugins/AUpdater/updater.log!
java.nio.file.NoSuchFileException: plugins/AUpdater/updater.log
        at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86) ~[?:1.8.0_151]
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102) ~[?:1.8.0_151]
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107) ~[?:1.8.0_151]
        at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:214) ~[?:1.8.0_151]
        at java.nio.file.spi.FileSystemProvider.newOutputStream(FileSystemProvider.java:434) ~[?:1.8.0_151]
        at java.nio.file.Files.newOutputStream(Files.java:216) ~[?:1.8.0_151]
        at java.nio.file.Files.write(Files.java:3351) ~[?:1.8.0_151]
        at me.zombie_striker.wcsr.Updater.log(Updater.java:480) [WorldChangeScreenRemover-1.0.2.jar:?]
        at me.zombie_striker.wcsr.Updater.<init>(Updater.java:85) [WorldChangeScreenRemover-1.0.2.jar:?]
        at me.zombie_striker.wcsr.Updater.<init>(Updater.java:118) [WorldChangeScreenRemover-1.0.2.jar:?]
        at me.zombie_striker.wcsr.Main.onEnable(Main.java:25) [WorldChangeScreenRemover-1.0.2.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) [spigot-1.12.2.jar-2018-03-09-0717:git-Spigot-c3093ef-7e94e65]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [spigot-1.12.2.jar-2018-03-09-0717:git-Spigot-c3093ef-7e94e65]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403) [spigot-1.12.2.jar-2018-03-09-0717:git-Spigot-c3093ef-7e94e65]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:381) [spigot-1.12.2.jar-2018-03-09-0717:git-Spigot-c3093ef-7e94e65]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:330) [spigot-1.12.2.jar-2018-03-09-0717:git-Spigot-c3093ef-7e94e65]
        at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:422) [spigot-1.12.2.jar-2018-03-09-0717:git-Spigot-c3093ef-7e94e65]
        at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:383) [spigot-1.12.2.jar-2018-03-09-0717:git-Spigot-c3093ef-7e94e65]
        at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:338) [spigot-1.12.2.jar-2018-03-09-0717:git-Spigot-c3093ef-7e94e65]
        at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272) [spigot-1.12.2.jar-2018-03-09-0717:git-Spigot-c3093ef-7e94e65]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545) [spigot-1.12.2.jar-2018-03-09-0717:git-Spigot-c3093ef-7e94e65]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
```

- An update directory and files were created, but not plugin-specific _plugins/WorldChangeScreenRemover/config.yml_; instead _plugins/AUpdater/global.yml_. This is completely non-standard. .To what does "global update" refer? I disable all updates and update notifications; I have an automagical update checker and web site. I set _updates:false_ in _global.yml_. Hopefully, that will result in no updates checks.
- The lack of change screen is nice, but the whiplash is significant. Can it be fixed?

**Comment by ZombieStriker** [comment]
1. The error is caused because the log file cannot be found. I'll make a patch for thi
2. This new directory is created because I am using an updater by ArsenArsen, which defaults the global.yml to its own directory. Global update refers to all the plugins that use the same util. If you do not want the plugin to update on its own, set it to false.
3. I am trying to fix it, however I have not found anything yet that produces a reliable fix. Once I find a solution, I will release an update.

**Comment by SlimeDog** [comment]
It is customary (but not required, I'll admit) to leave tickets open until they are resolved, meaning fixed rather than planned to be.

**Comment by SlimeDog** [comment]
> This new directory is created because I am using an updater by ArsenArsen, which defaults the global.yml to its own directory. Global update refers to all the plugins that use the same util. If you do not want the plugin to update on its own, set it to false.

I appreciate that, but one might want to control it per plugin, not globally.
