### ISSUE TITLE
WCSR not working at all (TacoSpigot 1.8.8 + Latest 1.8.8 ProtocolLib)

### ISSUE THREAD

**Issue by yorik100** [ZombieStriker/WorldChangeScreenRemover#10]
[13:09:18] [Server thread/INFO]: yorik100 issued server command: /world
[13:09:18] [Server thread/ERROR]: Could not pass event PlayerChangedWorldEvent to WorldChangeScreenRemover v1.0.13
org.bukkit.event.EventException
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:309) ~[UnionSpigot.jar:git-TacoSpigot-bf023c7d]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[UnionSpigot.jar:git-TacoSpigot-bf023c7d]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[UnionSpigot.jar:git-TacoSpigot-bf023c7d]
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:508) [UnionSpigot.jar:git-TacoSpigot-bf023c7d]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:493) [UnionSpigot.jar:git-TacoSpigot-bf023c7d]
at net.minecraft.server.v1_8_R3.PlayerList.moveToWorld(PlayerList.java:665) [UnionSpigot.jar:git-TacoSpigot-bf023c7d]
at org.bukkit.craftbukkit.v1_8_R3.entity.CraftPlayer.teleport(CraftPlayer.java:568) [UnionSpigot.jar:git-TacoSpigot-bf023c7d]
at com.earth2me.essentials.Teleport.now(Teleport.java:127) [EssentialsX-2.15.0.1.jar:?]
at com.earth2me.essentials.Teleport.teleport(Teleport.java:198) [EssentialsX-2.15.0.1.jar:?]
at com.earth2me.essentials.Teleport.teleport(Teleport.java:154) [EssentialsX-2.15.0.1.jar:?]
at com.earth2me.essentials.commands.Commandworld.run(Commandworld.java:69) [EssentialsX-2.15.0.1.jar:?]
at com.earth2me.essentials.commands.EssentialsCommand.run(EssentialsCommand.java:157) [EssentialsX-2.15.0.1.jar:?]
at com.earth2me.essentials.Essentials.onCommandEssentials(Essentials.java:517) [EssentialsX-2.15.0.1.jar:?]
at com.earth2me.essentials.Essentials.onCommand(Essentials.java:430) [EssentialsX-2.15.0.1.jar:?]
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) [UnionSpigot.jar:git-TacoSpigot-bf023c7d]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:143) [UnionSpigot.jar:git-TacoSpigot-bf023c7d]
at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:667) [UnionSpigot.jar:git-TacoSpigot-bf023c7d]
at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1178) [UnionSpigot.jar:git-TacoSpigot-bf023c7d]
at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:991) [UnionSpigot.jar:git-TacoSpigot-bf023c7d]
at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) [UnionSpigot.jar:git-TacoSpigot-bf023c7d]
at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) [UnionSpigot.jar:git-TacoSpigot-bf023c7d]
at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [UnionSpigot.jar:git-TacoSpigot-bf023c7d]
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_191]
at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_191]
at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [UnionSpigot.jar:git-TacoSpigot-bf023c7d]
at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:785) [UnionSpigot.jar:git-TacoSpigot-bf023c7d]
at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:422) [UnionSpigot.jar:git-TacoSpigot-bf023c7d]
at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:724) [UnionSpigot.jar:git-TacoSpigot-bf023c7d]
at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:627) [UnionSpigot.jar:git-TacoSpigot-bf023c7d]
at java.lang.Thread.run(Unknown Source) [?:1.8.0_191]
Caused by: java.lang.NoSuchMethodError: org.bukkit.entity.Player.sendTitle(Ljava/lang/String;Ljava/lang/String;III)V
at me.zombie_striker.wcsr.MagicPacketHolder.onWorldChange(MagicPacketHolder.java:353) ~[?:?]
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_191]
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_191]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_191]
at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_191]
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:307) ~[UnionSpigot.jar:git-TacoSpigot-bf023c7d]
... 29 more

**Comment by ZombieStriker** [comment]
This error should be fixed in the new update.
